### ISSUE TITLE
In grid view, Videos need to feature a screen cap instead of VITA loading screen.

### ISSUE THREAD

**Issue by inder243** [brianhorakh/vita#10]
(We are not getting the thumbnail at our end.){
                    bumps = 0;
                    created = "2016-04-15 00:21:43";
                    evid = "DD81D64A-02DB-11E6-A33D-D99FB462889C";
                    "media_url" = "http://www.vitatheapp.com/files/2016-04-15/07/DD81D64A-02DB-11E6-A33D-D99FB462889C.161.mp4";
                    mediaid = 161;
                    "thumb_url" = "http://www.vitatheapp.com/files/2016-04-15/07/DD81D64A-02DB-11E6-A33D-D99FB462889C-thumb.161.jpg";
                    uid = 100;
                    url = "http://www.vitatheapp.com/files/2016-04-15/07/DD81D64A-02DB-11E6-A33D-D99FB462889C.161.mp4";
                },
Fetching the thumbnail gives no image

**Comment by brianhorakh** [comment]
I believe this issue has been corrected (i just made a patch), can you please confirm?

**Comment by inder243** [comment]
![2016-05-31-111757_1366x768_scrot](https://cloud.githubusercontent.com/assets/7559712/15664509/1e77a12e-2722-11e6-98cf-081e57399881.png)

**Comment by brianhorakh** [comment]
I should have clarified -- the issue was resolved going forward. 

That image was uploaded 2015-05-09 --
Please upload a new image, previously uploaded thumbnails were not properly generated.
I can flush the db if you want to get rid of old ones, but I'd need to rewrite a script to regenerate all previous thumbnails to fix.

**Comment by inder243** [comment]
I have just uploaded one of the video and could not find any thumbnail created. Please refer thumbs =             (
                                {
                    bumps = 0;
                    created = "2016-05-31 23:42:25";
                    evid = "82F16844-27C5-11E6-B60E-88D178BD133F";
                    "media_url" = "http://www.vitatheapp.com/files/2016-06-01/06/82F16844-27C5-11E6-B60E-88D178BD133F.502.mp4";
                    mediaid = 502;
                    "thumb_url" = "http://www.vitatheapp.com/files/2016-06-01/06/82F16844-27C5-11E6-B60E-88D178BD133F-thumb.502.jpg";
                    uid = 100;
                    url = "http://www.vitatheapp.com/files/2016-06-01/06/82F16844-27C5-11E6-B60E-88D178BD133F.502.mp4";
                }
            );
            title = Vvvav;
        }
    );

Moreover, Please correct the output

"error_id" = 666;
    "error_msg" = "internal server error Can't locate object method \"fetchrow_hashref\" via package \"DBI::db\" at /httpd/vita/perllib/VITA.pm line 1302.\n";
    now = "2016-05-31 23:46:43";
    success = 0;

**Comment by inder243** [comment]
![screen shot 2016-06-01 at 12 11 18 pm](https://cloud.githubusercontent.com/assets/7559712/15700525/00eb6caa-27f2-11e6-86ae-d1f77ccca506.png)

Please refer the screenshot a box is created only. No display of image.

**Comment by brianhorakh** [comment]
both issues should now be corrected.

**Comment by inder243** [comment]
Done, Will close issue after testing it. Can you reduce the database entries for now. We have huge set of data, would love if you can delete few pictures and videos.

**Comment by SeanGuerrero** [comment]
Vakul, were you able to test and resolve this issue?

**Comment by inder243** [comment]
Tested the issue but wasn't able to get the desired output.
