### ISSUE TITLE
PW screen is good. User should populate current PW in order to change it.

### ISSUE THREAD

**Issue by inder243** [brianhorakh/vita#11]
We cannot let the user password be visible as far security breach are concerned. We need to make it hidden for unauthorized access.
Please let us know what needs to be done.

**Comment by brianhorakh** [comment]
This is only enabled during testing - already on my list of "go live" items to remove.

**Comment by inder243** [comment]
For testing can you please send us password in the web service(UserProfileInfo). Later on you can remove the same.

**Comment by brianhorakh** [comment]
PasswordPlainText will now appear in UserProfilesInfo

**Comment by SeanGuerrero** [comment]
I agree, the current Password in edit password isn't supposed to show.  The other Edit Screens should show current email, username, phone number... etc.  Change password should have to type in current password in order to change it.

**Comment by inder243** [comment]
We have showed user current password in corresponding screen for testing, will remove it later.
Will Close this issue after testing. Thanks
