### ISSUE TITLE
Require AWS Account for Vita

### ISSUE THREAD

**Issue by brianhorakh** [brianhorakh/vita#2]
Sean - still need access to an AWS account for push notifications and other services. Please email me credentials (don't post them here since it's public) and mark the issue as closed.

Thanks!

**Comment by SeanGuerrero** [comment]
I just emailed it to your gmail account Brian.  Please let me know that you have received.

**Comment by SeanGuerrero** [comment]
How do you close an issue?

**Comment by brianhorakh** [comment]
Sean I looked for this email - did you send it to my gru3hunt3r email address or another one?

**Comment by SeanGuerrero** [comment]
Just resent the email

**Comment by brianhorakh** [comment]
All good, just need certificates now from inder243
