### ISSUE TITLE
Need 2 parameters added to Eventlist API

### ISSUE THREAD

**Issue by SeanGuerrero** [brianhorakh/vita#24]
bumps = 0;
created = "2016-06-05 22:43:08";
evid = "274208AC-2BAB-11E6-9ECF-88D178BD133F";
"media_url" = "http://www.vitatheapp.com/files/2016-06-06/05/274208AC-2BAB-11E6-9ECF-88D178BD133F.503.mp4";
mediaid = 503;
"thumb_url" = "http://www.vitatheapp.com/files/2016-06-06/05/274208AC-2BAB-11E6-9ECF-88D178BD133F-thumb.503.jpg";
uid = 100;
url = "http://www.vitatheapp.com/files/2016-06-06/05/274208AC-2BAB-11E6-9ECF-88D178BD133F.503.mp4";

Here Above If under UID: you can add two parameters UserName and ProfilePic. That will subsequently decrease time and will help us fetching data easily.

Here is an Api response where we need information to be added

**Comment by brianhorakh** [comment]
The user UserName and ProfilePic are returned in the "Users":[] portion of the EventList response.
It may not have done this when the issue was opened, so I'm going to close this.
