### ISSUE TITLE
API ISSUES

### ISSUE THREAD

**Issue by inder243** [brianhorakh/vita#27]
We are getting some issue in APIs Response which I have listed below.....

1: The Caption is updated from Server side.
We are hitting this API to edit the Caption for a event Id.
http://www.vitatheapp.com/vita-api/EventMediaUpdate?authid=4F45325C-F71C-11E5-A06D-A7AA58C3F44C&uid=101&evid=06569A7C-ECAE-11E5-BFB5-A7AA58C3F44C&mediaid=694&caption=455

which is showing Successful message .But Its not updating the previous Caption.
http://www.vitatheapp.com/vita-api/EventList?evid=06569A7C-ECAE-11E5-BFB5-A7AA58C3F44C
1. we are not getting profile pic for some User id .
   http://www.vitatheapp.com/vita-api/UserProfileInfo?uid=0
2. Duplicity for User detail in EventList.
   http://www.vitatheapp.com/vita-api/EventList?lat=37.785834&lng=-122.406417&dist=10.000000

**Comment by brianhorakh** [comment]
Please create one separate issue per API call or test case.
Please include examples whenever possible.
It is also confusing when the same number (e.x. #1 above) is used more than once for separate issues.
Please post only one distinct issue per github "issue"

**Comment by brianhorakh** [comment]
response from: 
http://www.vitatheapp.com/vita-api/EventMediaUpdate?authid=4F45325C-F71C-11E5-A06D-A7AA58C3F44C&uid=101&evid=06569A7C-ECAE-11E5-BFB5-A7AA58C3F44C&mediaid=694&caption=455

The API call above is intended to update the caption of media id 694. 

{"success":true,"_sql-rv":1,"now":"2016-10-02 14:23:13","_sql":"update EventsMedia set evid='06569A7C-ECAE-11E5-BFB5-A7AA58C3F44C',caption='455',uid='101',id='694' where id='694' and uid='101' and evid='06569A7C-ECAE-11E5-BFB5-A7AA58C3F44C'"}

**Comment by brianhorakh** [comment]
I've modified the EventList API so it will not return media with "uid" of "0" 

This appears to have corrected the problem.
