### ISSUE TITLE
Recover Password not working -- Redis not accessible - port 6379 on vitadb

### ISSUE THREAD

**Issue by brianhorakh** [brianhorakh/vita#3]
Joe -

It seems there is possibly some magic firewall voodoo that prohibits 66.171.252.86 from accessing 66.171.252.87 via port 6379.   Is this possible?    After this is done please confirm recover password is working (temporary password tokens are stored in the redis on 66.171.252.87:6379)

[root@centos1 .ssh]# telnet vitadb 6379
Trying 66.171.252.87...
telnet: connect to address 66.171.252.87: Connection refused

[root@centos1 .ssh]# ssh vitadb
Last login: Tue May 24 06:28:30 2016 from 66.171.252.86
[root@centos2 ~]# iptables -L
Chain INPUT (policy ACCEPT)
target     prot opt source               destination
ACCEPT     all  --  anywhere             anywhere            state RELATED,ESTABLISHED
ACCEPT     icmp --  anywhere             anywhere
ACCEPT     all  --  anywhere             anywhere
ACCEPT     tcp  --  anywhere             anywhere            state NEW tcp dpt:ssh
ACCEPT     tcp  --  66.171.252.86        anywhere            state NEW tcp dpt:6379
ACCEPT     tcp  --  66.171.252.86        anywhere            state NEW tcp dpt:mysql
REJECT     all  --  anywhere             anywhere            reject-with icmp-host-prohibited

**Comment by jrmcelroy** [comment]
Got it working, just had to fix the redis config. The firewall wasn't the problem, was a redis port connection/binding connection issue. 

[root@centos1 ~]# telnet vitadb 6379
Trying 66.171.252.87...
Connected to vitadb.
Escape character is '^]'.

**Comment by brianhorakh** [comment]
I have temporarily brought up a redis server on the web-server until I'm able to reach joe and work around this.

**Comment by jrmcelroy** [comment]
I'm working on a harddrive and network issue right now. Should be able to talk later, but what is the issue? I replied to this and am able to connect to the redis server and port scan it and it works.

**Comment by brianhorakh** [comment]
Joe - sorry I missed your earlier comment, we're all good now.  Thanks!
