### ISSUE TITLE
Login should be username or email used at time of registration

### ISSUE THREAD

**Issue by inder243** [brianhorakh/vita#5]
We are unable to login via email:
http://www.vitatheapp.com/vita-api/UserLogin? Username=kavita.r@iapptechnologies.com&Password=qwerty&AuthType=vita

**Comment by brianhorakh** [comment]
I was not able to reproduce this.  The login seems to work for me.
Possibly related to redis server not available.

**Comment by SeanGuerrero** [comment]
Vakul, Was this taken addressed and tested?
